import re
import os
from torito_prototype.entity.config import Config, ProxyConfig, BridgeConfig

entryPattern = re.compile(
    r"(?P<directive>UseBridges |Bridge |HTTPProxy |HTTPProxyAuthenticator |HTTPSProxy |HTTPSProxyAuthenticator |Socks4Proxy |Socks5Proxy |Socks5ProxyUsername |Socks5ProxyPassword )(?P<args>.*)"
)

class TorrcRepository:
    path: str

    def __init__(self, path: str):
        # ファイルが存在するかチェック
        if not os.path.exists(path):
            raise FileNotFoundError(f"File not found: {path}")
        
        self.path = path

    def load(self) -> Config:
        with open(self.path, "r") as f:
            # インデックスを付与する
            lines = enumerate(f.readlines(), start=1)

        tmp = {
            "UseBridges": False,
            "Bridge": [],
            "HTTPProxy": [],
            "HTTPProxyAuthenticator": [],
            "HTTPSProxy": [],
            "HTTPSProxyAuthenticator": [],
            "Socks4Proxy": [],
            "Socks5Proxy": [],
            "Socks5ProxyUsername": [],
            "Socks5ProxyPassword": [],
            "others": []
        }

        for _, line in lines:
            match = entryPattern.match(line)
            if match is None:
                tmp["others"].append(line)
                continue

            directive = match.group("directive").strip()
            args = match.group("args").strip()

            match directive:
                case "UseBridges":
                    tmp["UseBridges"] = True if args == "1" else False
                case "Bridge":
                    tmp["Bridge"].append(args)
                case "HTTPProxy":
                    tmp["HTTPProxy"].append(args)
                case "HTTPProxyAuthenticator":
                    tmp["HTTPProxyAuthenticator"].append(args)
                case "HTTPSProxy":
                    tmp["HTTPSProxy"].append(args)
                case "HTTPSProxyAuthenticator":
                    tmp["HTTPSProxyAuthenticator"].append(args)
                case "Socks4Proxy":
                    tmp["Socks4Proxy"].append(args)
                case "Socks5Proxy":
                    tmp["Socks5Proxy"].append(args)
                case "Socks5ProxyUsername":
                    tmp["Socks5ProxyUsername"].append(args)
                case "Socks5ProxyPassword":
                    tmp["Socks5ProxyPassword"].append(args)
                case _:
                    tmp["others"].append(line)

            return Config(
                useBridge=tmp["UseBridges"],
                bridgeConfig=BridgeConfig(bridgeParams=tmp["Bridge"]),
                proxyConfig=ProxyConfig(
                    HTTPProxyParams=tmp["HTTPProxy"],
                    HTTPProxyAuthenticatorParams=tmp["HTTPProxyAuthenticator"],
                    HTTPSProxyParams=tmp["HTTPSProxy"],
                    HTTPSProxyAuthenticatorParams=tmp["HTTPSProxyAuthenticator"],
                    Socks4ProxyParams=tmp["Socks4Proxy"],
                    Socks5ProxyParams=tmp["Socks5Proxy"],
                    Socks5ProxyUsernameParams=tmp["Socks5ProxyUsername"],
                    Socks5ProxyPasswordParams=tmp["Socks5ProxyPassword"]
                ),
                others=tmp["others"]
            )
        
    def save(self, config: Config) -> None:
        with open(self.path, "w") as f:

            f.write("### This file was generated by torito_prototype ###\n")
            if config.useBridge:
                f.write("UseBridges 1\n")
            f.write("\n".join([f"Bridge {bridgeParam}" for bridgeParam in config.bridgeConfig.bridgeParams]) + "\n")
            f.write("\n".join([f"HTTPProxy {HTTPProxyParam}" for HTTPProxyParam in config.ProxyConfig.HTTPProxyParams]) + "\n")
            f.write("\n".join([f"HTTPProxyAuthenticator {HTTPProxyAuthenticatorParam}" for HTTPProxyAuthenticatorParam in config.ProxyConfig.HTTPProxyAuthenticatorParams]) + "\n")
            f.write("\n".join([f"HTTPSProxy {HTTPSProxyParam}" for HTTPSProxyParam in config.ProxyConfig.HTTPSProxyParams]) + "\n")
            f.write("\n".join([f"HTTPSProxyAuthenticator {HTTPSProxyAuthenticatorParam}" for HTTPSProxyAuthenticatorParam in config.ProxyConfig.HTTPSProxyAuthenticatorParams]) + "\n")
            f.write("\n".join([f"Socks4Proxy {Socks4ProxyParam}" for Socks4ProxyParam in config.ProxyConfig.Socks4ProxyParams]) + "\n")
            f.write("\n".join([f"Socks5Proxy {Socks5ProxyParam}" for Socks5ProxyParam in config.ProxyConfig.Socks5ProxyParams]) + "\n")
            f.write("\n".join([f"Socks5ProxyUsername {Socks5ProxyUsernameParam}" for Socks5ProxyUsernameParam in config.ProxyConfig.Socks5ProxyUsernameParams]) + "\n")
            f.write("\n".join([f"Socks5ProxyPassword {Socks5ProxyPasswordParam}" for Socks5ProxyPasswordParam in config.ProxyConfig.Socks5ProxyPasswordParams]) + "\n")
            f.write("### End of generated ###\n")
            f.write("\n".join(config.others) + "\n")