name: build with pyinstaller

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: sudo apt update && sudo apt install -y build-essential libpython3-dev libdbus-1-dev
      - run: pip install .
      - run: pyinstaller --onefile src/torito_prototype/main.py -n torito_prototype
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: torito_prototype
          path: dist/torito_prototype
